### ISSUE TITLE
Build Failure Under GHC v7.8.4 Cabal v1.22.4.0

### ISSUE THREAD

**Issue by fundamental** [dillonhuff/Folly#3]
After a fresh install of both GHC and Cabal this package fails to build from the official cabal version and from git. The error observed is:

```
src/Folly/Utils.hs:12:10:
    Not in scope: type constructor or class `Applicative'
```

I'm rather inexperienced with haskell, so my debugging so far has been limited to testing an older GHC 7.6.2/Cabal 1.10.2.0 and the newer version on two different slackware linux computers.

**Comment by dillonhuff** [comment]
I have modified the Error ADT. I suspect that the problem was related to the Applicative - Monad changes that were made in GHC 7.10 (I am using GHC 7.10.2).

Please try again and let me know what happens.

**Comment by fundamental** [comment]
This appears to have resolved the issue.
Thanks
